[workspace]
authors = ["YenochQin <yenochqin@hotmail.com>"]
channels = ["conda-forge"]
name = "CSFs_loader"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
rust = ">=1.91.1,<1.92"
