[workspace]
authors = ["YenochQin <yenochqin@hotmail.com>"]
channels = ["conda-forge"]
name = "CSFs_loader"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
rust = ">=1.92.0,<1.93"
gcc = ">=15.2.0,<15.3"
gcc_linux-64 = ">=15.2.0,<16"
gxx_linux-64 = ">=15.2.0,<16"
maturin = ">=1.10.2,<2"
patchelf = ">=0.17.2,<0.18"
python = "3.14.*"


